### ISSUE TITLE
MicroG icon disappeared from home launcher

### ISSUE THREAD

**Issue by tianyang-abc** [inotia00/VancedMicroG#11]
I'm working on Meizu 18 Pro, which is based on Android 11 with Flyme 9.3.0.0A OS. I could login by MicroG, and use ReVanced Youtube as well. The problem occured as the following:
Firstly, I uninstalled Vanced MicroG v0.2.24.220220. 
Then I installed inotia00/VancedMicroG the lastest v0.2.25.224113-224113003. 
I could not find the icon of the original MicroG at last.  ReVanced Youtube was broken because I was not login with MicroG. 
I could find the MicroG in the ALL APPLICATION in SETTING, but I could not launch it at all.

Any help is appreciated. Thanks!

**Comment by xdkernelx** [comment]
Try this
Go to Settings, Accounts and look for the Vanced microG one. Remove it and try to start YouTube Revanced again and login again with your microG account.

**Comment by inotia00** [comment]
![Screenshot_20221224-004426_Vanced microG](https://user-images.githubusercontent.com/108592928/209362286-84705b5e-0a9b-4958-8554-2fddb698c6a9.png)
this is not a bug
By default, MicroG is hidden in the app launcher

Open the MicroG Settings in ReVanced Settings, then change the `hide icon from launcher`setting to OFF
