### ISSUE TITLE
ChromeCast not working in youtube mods

### ISSUE THREAD

**Issue by jhonnyn5** [inotia00/VancedMicroG#14]
Many youtube mods use microg but their non-root variants are not able to connect to a chromecast.  Please fix it.

**Comment by inotia00** [comment]
Unfortunately, VancedMicroG implements only minimal functionality for login and receiving notifications from YouTube and YouTube Music.

Features such as ChromeCast v2, G Suite, Family Link, and Android Auto have been completely removed and will not work

Unfortunately, there are no plans to support these in the future, sorry
