### ISSUE TITLE
Can't login into youtube music vanced ver 4.27.50 with Vanced MicroG v0.2.26.224913

### ISSUE THREAD

**Issue by paisano117** [inotia00/VancedMicroG#17]
when i updated to Vanced MicroG v0.2.26.224913, I got logged out of youtube music vanced and can't log back in, it just shows "add account" and I clicked it and tried to log back in but it says I already logged in, I tried everything like uninstalling vanced microg and yt music vanced and still didn't work, and I am using youtube music vanced ver 4.27.50 because its the last version that allows playing songs on demand and seeking, please fix.

**Comment by inotia00** [comment]
Vanced Music v4.27.50 is outdated

If you are going to use an old version of Vanced Music, use an old version of Vanced MicroG

[Vanced MicroG v0.2.24.220220](https://github.com/TeamVanced/VancedMicroG/releases/tag/v0.2.24.220220-220220001)

**Comment by paisano117** [comment]
what if eventually newer youtube revanced versions might stop working with the old vanced microg that works with old vanced music, and I still update youtube revanced because it still works and because newer patches won't work on old youtube revanced versions or else ads will come back, its just vanced music that I have a problem with.
