### ISSUE TITLE
Supervised Google account won't log in

### ISSUE THREAD

**Issue by mariuszo73** [inotia00/VancedMicroG#18]
Not possible to add supervised (Family Link) child account.
Sony Xperia 10IV
Android 12

![rrRFlHS](https://user-images.githubusercontent.com/29626987/212560920-cafeb558-d4eb-463a-81bb-f064626a1e93.png)

**Comment by inotia00** [comment]
Unfortunately, VancedMicroG implements only minimal functionality for login and receiving notifications from YouTube and YouTube Music.

Features such as ChromeCast v2, G Suite, Family Link, and Android Auto have been completely removed and will not work

Unfortunately, there are no plans to support these in the future, sorry
