### ISSUE TITLE
How is this better than Normal Vanced Microg?

### ISSUE THREAD

**Issue by Nitroandaccounts** [inotia00/VancedMicroG#2]
Is there any big changes except dark mode? Otherwise, why fix what isn’t broken?

**Comment by inotia00** [comment]
Please read the changelog on the release page

**Comment by Nitroandaccounts** [comment]
I do.

**Comment by Nitroandaccounts** [comment]
Says things like updated library? But what does that do? How does it help if normal microg isn’t broken.

**Comment by Nitroandaccounts** [comment]
@inotia00

**Comment by inotia00** [comment]
1. Latest PlayService library applied
2. removed code for chromecast v2 causing battery drain (microg doesn't fully support chrome cast v2 from the beginning)
3. removed code for google location (does not used at Vanced/ReVanced)
4. Supports SPOOFED_PACKAGE_SIGNATURE supported by ReVanced
5. Added translation and fully supports dark theme

**Comment by Nitroandaccounts** [comment]
@inotia00 what is the direct benefit of 1, 3, 4

**Comment by inotia00** [comment]
1. This is as similar to updating WebView on your device.
Simply bumping the base version

3. Remove the dummy code that is not used.

4. There is no problem right now, but if Google later read the GMS's package name (Microg's package name) in YouTube, you can see that it is a modified YouTube app.
(A typical example, a few months ago, Google checked the package name, and when it was a modified YouTube app, it had made it impossible to play on the server. [#1](https://www.reddit.com/r/Vanced/comments/ykbvma/question_why_is_this_coming_up_i_downloaded/) )

To prevent this, the package name of Microg is deceived by GMS's package name.

**Comment by inotia00** [comment]
I indicated the changelog of github releases and provided an additional explanation according to the request.

If you are still confused, just use the official Vanced MicroG (Teamvanced)

**Comment by Nitroandaccounts** [comment]
I understand most of it now, thanks!
