### ISSUE TITLE
notification issue

### ISSUE THREAD

**Issue by iamthelara** [inotia00/VancedMicroG#20]
![Screenshot_20230117_232431_Vanced microG](https://user-images.githubusercontent.com/50659607/212975079-b02306e8-f144-4f9a-b9b0-987291960004.jpg)
It shows this(not connected).

Is this normal?

**Comment by dark-caster** [comment]
Try to "force stop" the Vanced microG, after YouTube revanced and restart the phone to see if it stays connected again. While in "disconnected" status it means you will not receive pop-up notifications.

**Comment by inotia00** [comment]
refer it https://github.com/inotia00/VancedMicroG/issues/1#issuecomment-1295962488
