### ISSUE TITLE
Cannot load video in some country

### ISSUE THREAD

**Issue by hoanghainguyen133** [inotia00/VancedMicroG#25]
![Screenshot_20230128-151147.png](https://user-images.githubusercontent.com/121709602/215255039-46f2d358-1798-482f-a3aa-9dab0300052d.png)

**Comment by degmans117** [comment]
I have same issue in Bulgaria. After use vpn with UK server everything is working fine.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
