### ISSUE TITLE
Problem with playing vidios

### ISSUE THREAD

**Issue by Struggler477** [inotia00/VancedMicroG#30]
Every time i open a video it plays normally then it stops to load, the video goes black and never loads until you close it and reopen it.
Checked my connection, it's not the problem.
The longest a video ever went without going black was a minute

**Comment by FalcoNn0703** [comment]
Yes! I had a same issue. I tried everything. But nah. The videos keep stopping after a minute. Please someone enlight us about this goofy ah problem.

**Comment by KiranPranay** [comment]
> 

For now, use without signing in.

**Comment by sensboston** [comment]
I hope, @inotia00 (or someone from the ReVanced team) will be able to fix MicroG issue soon.

**Comment by inotia00** [comment]
https://github.com/inotia00/ReVanced_Extended/issues/141
