### ISSUE TITLE
Could you please fix this (this was broken in original Vanced MicroG too)?

### ISSUE THREAD

**Issue by Nitroandaccounts** [inotia00/VancedMicroG#4]
Can you add support for cast V2 please? This would be a lifesaver!

**Comment by Nitroandaccounts** [comment]
https://github.com/vitalidze/chromecast-java-api-v2

**Comment by am2222** [comment]
This would be awesome if can have it.

**Comment by inotia00** [comment]
Unfortunately, VancedMicroG implements only minimal functionality for login and receiving notifications from YouTube and YouTube Music.

Features such as ChromeCast v2, G Suite, Family Link, and Android Auto have been completely removed and will not work

Unfortunately, there are no plans to support these in the future, sorry
