### ISSUE TITLE
G Suite accounts do not work with Vanced MicroG

### ISSUE THREAD

**Issue by jbritain** [inotia00/VancedMicroG#6]
This was a problem on the original VancedMicroG which was never addressed.

The [issue on the Vanced repo](https://github.com/TeamVanced/Vanced/issues/115) has more details.

**Comment by inotia00** [comment]
Unfortunately, VancedMicroG implements only minimal functionality for login and receiving notifications from YouTube and YouTube Music.

Features such as ChromeCast v2, G Suite, Family Link, and Android Auto have been completely removed and will not work

Unfortunately, there are no plans to support these in the future, sorry
