### ISSUE TITLE
Vanced MicroG Update 

### ISSUE THREAD

**Issue by TheGoldenSun** [inotia00/VancedMicroG#9]
Hi, it seems that YouTube wants me to update my YouTube revanced app since I'm using the non-root version it wouldn't be able to update due to the pre-release I downloaded in here has bug errors apparently, it has been an issue for most people who has been using YouTube revanced as well for a long time thanks to the YouTube company who always updates their app with more improvements daily, so I was hoping if this issue would be resolved with an idea.

**Comment by inotia00** [comment]
So what's the issue with Vanced MicroG?
